name: ifoot_academy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.5.0
  json_annotation: ^4.6.0
  flutter_launcher_icons: ^0.9.2
  freezed_annotation: ^2.1.0
  rxdart: ^0.27.7
  flutter_redux: ^0.8.2
  redux: ^5.0.0
  redux_epics: ^0.15.0
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  badges: ^3.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_calendar: ^20.2.49

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  build_runner: ^2.2.0
  table_calendar: ^3.1.2
  flutter_lints: ^2.0.1
  flutter_datetime_picker: ^1.5.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/login.jpg
    - assets/images/regis.jpg
    - assets/Logo/logo.png
