name: ifoot_academy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.5.0
  json_annotation: ^4.6.0

  freezed_annotation: ^2.1.0
  rxdart: ^0.27.7

  flutter_redux: ^0.8.2
  redux: ^5.0.0
  redux_epics: ^0.15.0

  http: ^1.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  freezed: ^2.1.0
  build_runner: ^2.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/Couverture.jpg
    - assets/Logo/logo.png
