name: ifoot_academy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_app_check: ^0.2.2+7
  firebase_auth: ^4.20.0
  firebase_storage: ^11.1.0
  percent_indicator: ^4.2.3
  cloud_firestore: ^4.5.0
  image_picker: ^0.8.6
  flutter_gcaptcha_v3: 2.0.4
  json_annotation: ^4.6.0
  flutter_launcher_icons: ^0.9.2
  freezed_annotation: ^2.1.0
  rxdart: ^0.27.7
  http: ^0.13.1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.6
  badges: ^3.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_calendar: ^20.2.49
  flutter_local_notifications: ^9.1.4  
  timezone: ^0.8.0
  permission_handler: ^10.2.0  # Use the latest version
  provider: ^6.0.1
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.2.1
  firebase_messaging: ^14.0.1
  animations: ^2.0.11
  dropdown_search: ^5.0.6
  font_awesome_flutter: ^10.4.0
  flutter_staggered_animations: ^1.1.1
  intl_phone_number_input: ^0.7.4
  google_maps_flutter: ^2.2.5
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^2.0.0
  geolocator: ^12.0.0
  fl_chart: ^0.40.0 # Try a stable, older version if the current one is not compatible.
  cloud_functions: ^4.7.6
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  build_runner: ^2.2.0
  table_calendar: ^3.1.2
  flutter_lints: ^2.0.1
  flutter_datetime_picker: ^1.5.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/Logo/logo.png
    - assets/images/default_player.png
    - assets/images/
